{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.name }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.backend.name }}
    component: backend
type: Opaque
data:
  {{- if .Values.secret.data }}
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- else }}
  # Add your secret data here
  # database-password: ""
  # api-key: ""
  # jwt-secret: ""
  {{- end }}
---
{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.frontend.name }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.frontend.name }}
    component: frontend
type: Opaque
data:
  {{- if .Values.secret.data }}
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- else }}
  # Add your secret data here
  # api-endpoint-key: ""
  {{- end }}
{{- end }}
{{- end }}